<p><span style="font-weight: 400;">Am distribuit aplicația MVP și chestionarele celor 9 participanți (din milestone-ul 2), dintre care 5 au fost mentees și 4 mentori. Am ales să oferim chestionarele celor 9 persoane, deoarece aceștia au fost intervievați anterior pentru a identifica dacă există o problemă reală &icirc;n domeniul mentoratului pe care aplicația o rezolvă. Interviurile inițiale ne-au ajutat să &icirc;nțelegem mai bine nevoile și dificultățile cu care se confruntă at&acirc;t mentees, c&acirc;t și mentori, și ne-au confirmat existența unei posibile soluții prin aplicația noastră. De asemenea, prin aceste interviuri am putut obține o primă impresie despre cerințele și dorințele utilizatorilor.</span></p>
<p><span style="font-weight: 400;">&Icirc;mpărțind aceste 9 persoane &icirc;n două grupuri (mentee și mentori), am putut adresa &icirc;ntrebări mai specifice pentru fiecare dintre aceștia, &icirc;n funcție de rolul lor și interacțiunile diferite cu aplicația. Iată c&acirc;teva motive pentru care am ales să le oferim chestionarul:</span></p>
<h3><strong>1. Confirmarea problemelor identificate &icirc;n interviuri</strong></h3>
<p><span style="font-weight: 400;">Interviurile ne-au ajutat să identificăm posibilele provocări și nevoi, dar chestionarele ne-au permis să aprofundăm aceste aspecte. Deși interviurile au fost utile pentru obținerea unor informații calitative, chestionarele ne-au oferit un cadru mai structurat și cantitativ pentru a valida aceste informații. Astfel, chestionarele au ajutat să confirmăm dacă problemele identificate &icirc;n interviuri sunt cu adevărat relevante și &icirc;nt&acirc;lnite pe scară largă &icirc;n r&acirc;ndul utilizatorilor.</span></p>
<h3><strong>2. Colectarea unui feedback mai detaliat și sistematic</strong></h3>
<p><span style="font-weight: 400;">Prin interviuri, am obținut informații valoroase despre nevoile și provocările utilizatorilor. Totuși, pentru a &icirc;nțelege cu adevărat amploarea problemelor și pentru a putea evalua mai ușor feedbackul, am considerat că este esențial să adunăm răspunsuri mai detaliate și sistematice prin chestionare. Acestea ne-au oferit o viziune mai clară asupra aspectelor specifice ale aplicației care trebuie &icirc;mbunătățite, precum interfața, procesul de rezervare sau funcțiile de comunicare.</span></p>
<h3><strong>3. Evaluarea reacțiilor la funcționalitățile MVP-ului</strong></h3>
<p><span style="font-weight: 400;">Chestionarele au fost o metodă ideală pentru a evalua reacțiile utilizatorilor față de funcționalitățile cheie ale aplicației MVP. După ce aceștia au testat aplicația, am dorit să colectăm informații precise despre cum au perceput utilizatorii acele funcționalități, precum căutarea mentorilor, programarea sesiunilor, interacțiunile &icirc;n cadrul sesiunilor live sau evaluarea mentorilor. &Icirc;n acest sens, chestionarele au oferit o metodă eficientă de a colecta date concrete despre experiența lor.</span></p>
<h3><strong>4. Validarea ipotezelor despre aplicabilitatea aplicației</strong></h3>
<p><span style="font-weight: 400;">Inițial, am lansat aplicația pentru a valida dacă există o cerere reală și un interes din partea utilizatorilor pentru serviciul de mentorat digitalizat. Chestionarele ne-au permis să obținem date care să sprijine sau să infirme ipotezele noastre legate de aplicabilitatea soluției și dacă aplicația răspunde &icirc;ntr-adevăr la nevoile utilizatorilor. Aceste date sunt esențiale pentru ajustarea și &icirc;mbunătățirea aplicației &icirc;nainte de a o lansa la scară mai largă.</span></p>
<h3><strong>5. Separarea feedback-ului pe baza rolurilor utilizatorilor</strong></h3>
<p><span style="font-weight: 400;">Av&acirc;nd două grupuri distincte &ndash; mentees și mentori &ndash; am avut nevoie de un feedback separat pentru fiecare categorie. Chestionarele personalizate ne-au permis să adunăm informații specifice legate de nevoile, dificultățile și satisfacția fiecărui grup &icirc;n parte, iar acest lucru este esențial pentru ajustarea aplicației la cerințele și comportamentele fiecărui utilizator. Mentees sunt interesați &icirc;n mod special de căutarea unui mentor și de gestionarea sesiunilor, &icirc;n timp ce mentori au nevoie de funcționalități pentru administrarea disponibilității și gestionarea clienților.</span></p>
<h3><strong>6. Obținerea unui feedback obiectiv</strong></h3>
<p><span style="font-weight: 400;">Deși interviurile ne-au oferit informații utile și mai detaliate, acestea au fost discuții deschise și subiective. Chestionarele au fost o metodă mai obiectivă de a colecta date, asigur&acirc;ndu-ne că toți participanții sunt &icirc;ntrebați despre aceleași aspecte și &icirc;n același mod. Acest lucru a garantat că avem un feedback uniform și comparabil din partea celor 9 utilizatori, ceea ce este esențial pentru analiza și &icirc;mbunătățirea aplicației.</span></p>
<p><span style="font-weight: 400;">&Icirc;n concluzie, oferirea chestionarului celor 9 participanți a fost o continuare logică a interviurilor inițiale, permiț&acirc;ndu-ne să validăm și să extindem informațiile obținute, să colectăm date mai structurate și să obținem o evaluare detaliată a aplicației MVP. Aceste chestionare ne-au furnizat dovezi valoroase despre relevanța și aplicabilitatea aplicației, precum și despre nevoile utilizatorilor, fiind astfel un pas esențial pentru validarea MVP-ului.</span></p>
<p><span style="font-weight: 400;">&Icirc;ntrebările și răspunsurile mentee-ilor</span></p>
<p><span style="font-weight: 400;">Link - </span><a href="https://docs.google.com/forms/d/e/1FAIpQLSeUA2xr2YcVIZLmUSz87A_yOM2q7oZ2x9Jv6arSR6dYkRbzow/viewform?usp=header"><span style="font-weight: 400;">https://docs.google.com/forms/d/e/1FAIpQLSeUA2xr2YcVIZLmUSz87A_yOM2q7oZ2x9Jv6arSR6dYkRbzow/viewform?usp=header</span></a></p>
<p><br /><br /></p>
<img src="{{ asset('storage/images/m8_1.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_2.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_3.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_4.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_5.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_6.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_7.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_8.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_9.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_10.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_11.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_12.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_13.png') }}" class="img-fluid my-1 w-100">


<p><span style="font-weight: 400;">&Icirc;ntrebările și răspunsurile mentorilor</span></p>
<p><span style="font-weight: 400;">Link - https://docs.google.com/forms/d/e/1FAIpQLSfUyl-Dvmd6bHqDTZvIuqE9e9J-iMW5M3M4nOJwIeP5cWp5zg/viewform?usp=header</span></p>
<img src="{{ asset('storage/images/m8_14.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_15.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_16.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_17.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_18.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_19.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_20.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_21.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_22.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_23.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_24.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_25.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_26.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_27.png') }}" class="img-fluid my-1 w-100">
<img src="{{ asset('storage/images/m8_28.png') }}" class="img-fluid my-1 w-100">

<h3><strong>Comentarii asupra feedback-ului utilizatorilor:</strong></h3>
<h4><strong>1. Funcționalitatea cea mai utilă</strong></h4>
<p><span style="font-weight: 400;">&Icirc;n cadrul primului chestionar, majoritatea utilizatorilor au apreciat </span><strong>filtrarea mentorilor pe baza prețului și disponibilității</strong><span style="font-weight: 400;">, </span><strong>sistemul de rezervare</strong><span style="font-weight: 400;"> și </span><strong>profilurile detaliate ale mentorilor</strong><span style="font-weight: 400;">. Aceste funcționalități sunt esențiale pentru experiența utilizatorilor, &icirc;ntruc&acirc;t ajută la economisirea timpului și la crearea unei experiențe de căutare și rezervare mai eficiente. Aceste răspunsuri sugerează că utilizatorii apreciază ușurința &icirc;n navigare și transparența &icirc;n alegerea mentorului potrivit. De asemenea, </span><strong>vizualizarea profilului mentorului</strong><span style="font-weight: 400;"> a fost, de asemenea, apreciată, ceea ce confirmă importanța detaliilor legate de expertiza mentorului.</span></p>
<p><span style="font-weight: 400;">&Icirc;n al doilea chestionar, </span><strong>calendarul integrat</strong><span style="font-weight: 400;"> și </span><strong>client management</strong><span style="font-weight: 400;"> au fost menționate ca fiind cele mai utile funcționalități. Acestea sunt elemente esențiale pentru mentori, ajut&acirc;ndu-i să &icirc;și gestioneze mai bine timpul și să răspundă cerințelor clienților lor. De asemenea, funcționalitatea de </span><strong>creare a unui profil detaliat</strong><span style="font-weight: 400;"> este un punct forte, at&acirc;t pentru mentori, c&acirc;t și pentru mentees, &icirc;ntruc&acirc;t o descriere clară a expertizei și disponibilității este crucială pentru alegerea mentorului.</span></p>
<h4><strong>2. Funcționalitatea care a creat dificultăți</strong></h4>
<p><span style="font-weight: 400;">&Icirc;n primul chestionar, </span><strong>dificultățile &icirc;nt&acirc;mpinate</strong><span style="font-weight: 400;"> au fost variate. Unii utilizatori au raportat probleme legate de </span><strong>selectarea orei pentru programarea sesiunii</strong><span style="font-weight: 400;">, ceea ce sugerează că procesul de rezervare ar putea necesita &icirc;mbunătățiri &icirc;n ceea ce privește interfața sau logica de selecție a orei. Altele au menționat </span><strong>lipsa de informații suficiente despre mentorii</strong><span style="font-weight: 400;">, ceea ce indică faptul că detaliile de profil ar trebui extinse pentru a oferi mai multe informații relevante, precum experiența profesională și domeniile de expertiză. De asemenea, unii utilizatori au menționat că </span><strong>&icirc;ncărcarea paginilor este lentă</strong><span style="font-weight: 400;">, ceea ce poate afecta experiența utilizatorului și sugerează că optimizarea vitezei aplicației ar trebui să fie o prioritate.</span></p>
<p><span style="font-weight: 400;">&Icirc;n al doilea chestionar, dificultățile exprimate au fost legate de </span><strong>vizualizarea istoricului sesiunilor</strong><span style="font-weight: 400;"> și </span><strong>vizualizarea ordinii sesiunilor cronologic</strong><span style="font-weight: 400;">, ceea ce sugerează că ar fi nevoie de o reorganizare mai clară și mai intuitivă a acestora &icirc;n aplicație. Această observație poate indica faptul că utilizatorii ar beneficia de o structură mai coerentă a istoricului sesiunilor, care să includă opțiuni de filtrare și sortare ușor de utilizat.</span></p>
<h4><strong>3. Funcționalități suplimentare dorite</strong></h4>
<p><span style="font-weight: 400;">&Icirc;n ambele chestionare, utilizatorii au menționat funcționalități care pot &icirc;mbunătăți aplicația. &Icirc;n primul chestionar, utilizatorii au sugerat </span><strong>integrarea cu Google Calendar</strong><span style="font-weight: 400;"> pentru a gestiona mai ușor sesiunile, </span><strong>notificări pentru sesiunile programate</strong><span style="font-weight: 400;">, și o funcționalitate de </span><strong>feedback pentru mentorii</strong><span style="font-weight: 400;">. Aceste funcționalități vor contribui semnificativ la &icirc;mbunătățirea experienței utilizatorului, deoarece vor facilita gestionarea sesiunilor și &icirc;mbunătățirea comunicării &icirc;ntre mentee și mentor.</span></p>
<p><span style="font-weight: 400;">&Icirc;n al doilea chestionar, sugestiile includ </span><strong>integrarea unui calendar</strong><span style="font-weight: 400;"> și </span><strong>&icirc;mbunătățirea vitezei paginii</strong><span style="font-weight: 400;">, indic&acirc;nd &icirc;ncă o dată importanța unei performanțe optime și a unui sistem de gestionare mai eficient al sesiunilor. De asemenea, utilizatorii ar dori </span><strong>posibilitatea de a &icirc;ncărca documente sau resurse partajate</strong><span style="font-weight: 400;"> &icirc;n timpul sesiunilor, ceea ce sugerează o cerere pentru o experiență mai interactivă și completă. Integrarea </span><strong>sesiunii video &icirc;n aplicație</strong><span style="font-weight: 400;"> este, de asemenea, un punct cheie, ceea ce sugerează că utilizatorii preferă o soluție complet integrată, fără a fi necesar să utilizeze platforme externe.</span></p>
<h4><strong>4. Schimbări necesare pentru &icirc;mbunătățirea aplicației</strong></h4>
<p><span style="font-weight: 400;">Feedback-ul privind &icirc;mbunătățirile sugerează c&acirc;teva aspecte cheie ce trebuie abordate. &Icirc;n primul chestionar, utilizatorii au recomandat </span><strong>optimizarea vitezei aplicației</strong><span style="font-weight: 400;"> și </span><strong>crearea unor ghiduri vizuale pentru utilizatorii noi</strong><span style="font-weight: 400;">, ceea ce indică o nevoie de a face aplicația mai rapidă și mai ușor de utilizat, &icirc;n special pentru utilizatorii mai puțin tehnici. De asemenea, </span><strong>secțiunea de &icirc;ntrebări frecvente</strong><span style="font-weight: 400;"> și </span><strong>tutorialele</strong><span style="font-weight: 400;"> sunt considerate esențiale pentru a ajuta utilizatorii să se familiarizeze mai ușor cu aplicația.</span></p>
<p><span style="font-weight: 400;">&Icirc;n al doilea chestionar, utilizatorii au menționat că ar trebui </span><strong>&icirc;mbunătățită viteza paginii</strong><span style="font-weight: 400;">, ceea ce este un punct de &icirc;ngrijorare, iar integrarea unui </span><strong>calendar</strong><span style="font-weight: 400;"> și a </span><strong>sesiunilor video &icirc;n aplicație</strong><span style="font-weight: 400;"> sunt solicitări importante, deoarece aceste &icirc;mbunătățiri vor spori funcționalitatea și accesibilitatea aplicației.</span></p>
<h3><strong>Concluzii și evaluarea MVP-ului:</strong></h3>
<p><span style="font-weight: 400;">&Icirc;n urma analizării feedback-ului, putem spune că </span><strong>MVP-ul a trecut o primă validare</strong><span style="font-weight: 400;"> din partea utilizatorilor. Acesta răspunde unor nevoi esențiale, cum ar fi filtrarea mentorilor, rezervarea sesiunilor, și vizualizarea profilurilor mentorilor, iar funcționalitățile menționate de utilizatori (cum ar fi calendarul integrat și managementul clienților) sunt considerate utile.</span></p>
<p><span style="font-weight: 400;">Cu toate acestea, există c&acirc;teva domenii unde aplicația poate fi &icirc;mbunătățită:</span></p>
<ul>
<li style="font-weight: 400;"><strong>Optimizarea vitezei aplicației</strong><span style="font-weight: 400;"> este o prioritate, av&acirc;nd &icirc;n vedere că utilizatorii au semnalat &icirc;nt&acirc;rzieri &icirc;n &icirc;ncărcarea paginilor.</span></li>
<li style="font-weight: 400;"><strong>&Icirc;mbunătățirea structurii istoricului sesiunilor</strong><span style="font-weight: 400;"> și </span><strong>vizualizarea acestora &icirc;ntr-o ordine cronologică</strong><span style="font-weight: 400;"> sunt necesare pentru a facilita navigarea &icirc;n aplicație.</span></li>
<li style="font-weight: 400;"><strong>Integrarea sesiunilor video și a funcționalităților pentru &icirc;ncărcarea de resurse partajate</strong><span style="font-weight: 400;"> va face aplicația mai completă și mai interactivă.</span></li>
</ul>
<p><span style="font-weight: 400;">De asemenea, este important să se implementeze funcționalități suplimentare, cum ar fi </span><strong>integrarea cu Google Calendar</strong><span style="font-weight: 400;">, </span><strong>notificări pentru sesiuni</strong><span style="font-weight: 400;"> și </span><strong>sistem de feedback pentru mentori</strong><span style="font-weight: 400;">, pentru a &icirc;mbunătăți experiența generală a utilizatorilor.</span></p>
<p><span style="font-weight: 400;">&Icirc;n concluzie, aplicația este pe drumul cel bun, dar mai necesită ajustări și &icirc;mbunătățiri pentru a răspunde complet nevoilor utilizatorilor. Continuarea testării și &icirc;mbunătățirii MVP-ului va asigura succesul &icirc;n fazele ulterioare de dezvoltare și scalare a produsului.</span></p>
<p><span style="font-weight: 400;">&Icirc;n ceea ce privește validarea plății, am testat opțiunea de a rezerva sesiuni și am observat interes crescut pentru utilizarea platformei. Deși &icirc;ncă nu am implementat plăți directe &icirc;n MVP, feedback-ul pozitiv și numărul de sesiuni rezervate sugerează că utilizatorii ar fi dispuși să plătească pentru serviciile de mentorat.</span></p>
<p><span style="font-weight: 400;">&Icirc;n urma testării MVP-ului, am reușit să atragem deja 15 mentee &icirc;nregistrați pe platformă și 4 mentori care oferă sesiuni de mentorat. Acest lucru demonstrează interesul real al utilizatorilor pentru aplicația noastră și confirmă validitatea conceptului. Deși MVP-ul este &icirc;ncă &icirc;n stadiu de dezvoltare, numărul de utilizatori activi și mentori care s-au alăturat platformei reprezintă un semn pozitiv al cererii pentru un astfel de serviciu. &Icirc;n continuare, ne concentrăm pe &icirc;mbunătățirea funcționalităților și pe adăugarea unor opțiuni suplimentare care să răspundă mai bine nevoilor utilizatorilor.</span></p>